name = "forward-to-slack-webhook"
compatibility_date = "2024-08-18"
#compatibility_flags = [ "nodejs_compat" ]
node_compat = true
main = "src/index.ts"

[vars]
WEBHOOK_KEY = ""
SLACK_CHANNEL = ""
SLACK_TOKEN = ""
TG_TOKEN = ""
